### ISSUE TITLE
Cleanup Stale Feature Flags

### ISSUE THREAD

**Issue by kageiit** [gitarcode/unleash#664]
We have some dead code behind feature flags that have been rolled out fully. We need to clean these up in code

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup showInactiveUsers=false

**Comment by krishmas** [comment]
dev @gitar-bot cleanup googleAuthEnabled=true

**Comment by krishmas** [comment]
dev @gitar-bot cleanup googleAuthEnabled=true

**Comment by krishmas** [comment]
dev @gitar-bot cleanup googleAuthEnabled=true

**Comment by krishmas** [comment]
dev @gitar-bot cleanup googleAuthEnabled=true

**Comment by krishmas** [comment]
dev @gitar-bot cleanup googleAuthEnabled=true

**Comment by krishmas** [comment]
staging @gitar-bot cleanup projectOverviewRefactor=false

**Comment by krishmas** [comment]
staging @gitar-bot cleanup projectOverviewRefactor=false

**Comment by krishmas** [comment]
@gitar-bot cleanup projectOverviewRefactor=false

**Comment by krishmas** [comment]
staging @gitar-bot cleanup inMemoryScheduledChangeRequests=true

**Comment by krishmas** [comment]
staging @gitar-bot cleanup inMemoryScheduledChangeRequests=true

**Comment by krishmas** [comment]
staging @gitar-bot cleanup inMemoryScheduledChangeRequests=true

**Comment by krishmas** [comment]
staging @gitar-bot cleanup inMemoryScheduledChangeRequests=true

**Comment by ketkarameya** [comment]
staging @gitar-bot cleanup increaseUnleashWidth=true

**Comment by ketkarameya** [comment]
staging @gitar-bot cleanup applicationOverviewNewQuery=true

**Comment by ketkarameya** [comment]
staging @gitar-bot cleanup applicationOverviewNewQuery=true

**Comment by ketkarameya** [comment]
staging @gitar-bot cleanup applicationOverviewNewQuery=true

**Comment by ketkarameya** [comment]
staging @gitar-bot cleanup applicationOverviewNewQuery=true

**Comment by ketkarameya** [comment]
staging @gitar-bot cleanup killInsightsUI=true
